### ISSUE TITLE
How to get the directory in which i created the file or folder?

### ISSUE THREAD

**Issue by EvilFreelancer** [undefinedSpace/daemon#6]
My ./file_status work on /home/pasha/Documents/Repository/undefinedSpace/
For example i create file into daemon folder:

File "/home/pasha/Documents/Repository/undefinedSpace/daemon/asd" has been created.
[{"type":"file","event":"IS_CREATED","name":"asd","inode":"2240884","time":"1487004992","crc":"0"}]

And I have a question, how to get the parent folder (inode?) of file which was created?

**Comment by B0mbo** [comment]
You can take a look at new field "parent" inside JSON request.
Done.
